contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #wombat channel"
    url: https://nfcore.slack.com/channels/wombat
    about: Discussion about the nf-core/wombat pipeline
